"""create products table

Revision ID: 076d0389aadf
Revises: ac4a2ffd6b53
Create Date: 2026-10-04 14:01:58.727775

"""
from alembic import op
import sqlalchemy as sa


revision = '076d0389aadf'
down_revision = 'ac4a2ffd6b53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_sku', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('supplier_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_price_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_stock_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('compliance_flag', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
