"""create remaining tables

Revision ID: 3e336b8276a9
Revises: 076d0389aadf
Create Date: 2026-10-04 14:12:23.730925

"""
from alembic import op
import sqlalchemy as sa


revision = '3e336b8276a9'
down_revision = '076d0389aadf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_health_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('late_shipment_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('order_defect_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valid_tracking_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('destination_country', sa.String(), nullable=False),
    sa.Column('avg_days', sa.Integer(), nullable=True),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('amazon_asin', sa.String(), nullable=True),
    sa.Column('amazon_sku', sa.String(), nullable=True),
    sa.Column('listed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margin_at_listing', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amazon_order_id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('destination_country', sa.String(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_decision', sa.String(), nullable=True),
    sa.Column('supplier_purchase_id', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amazon_order_id')
    )
    op.create_table('risk_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('check_name', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transactions')
    op.drop_table('risk_checks')
    op.drop_table('orders')
    op.drop_table('listings')
    op.drop_table('shipping_routes')
    op.drop_table('account_health_snapshots')
    # ### end Alembic commands ###
