"""create suppliers table

Revision ID: ac4a2ffd6b53
Revises: 
Create Date: 2026-10-04 10:35:16.359414

"""
from alembic import op
import sqlalchemy as sa


revision = 'ac4a2ffd6b53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('blind_shipping_confirmed', sa.Boolean(), nullable=False),
    sa.Column('contact_method', sa.String(), nullable=True),
    sa.Column('api_available', sa.Boolean(), nullable=False),
    sa.Column('api_credentials', sa.JSON(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    # ### end Alembic commands ###
