"""add reason to risk_checks

Revision ID: bafc7d9b5a19
Revises: 3e336b8276a9
Create Date: 2026-10-09 10:57:59.360877

"""
from alembic import op
import sqlalchemy as sa


revision = 'bafc7d9b5a19'
down_revision = '3e336b8276a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_checks', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_checks', 'reason')
    # ### end Alembic commands ###
